### PR TITLE
Feauture/es2015 module

### LINKED ISSUE #47: Support ESModule
Currently, when using `@brightlayer-ui/colors` with angular, the compiler throws the following warning : 

```
XXXX.js depends on '@brightlayer-ui/colors'. CommonJS or AMD dependencies can cause optimization bailouts.
```

If i'm correct, this can be fixed by shipping a ES Module version of the package. 

Could you look into it ? 

Thx

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #47 

#### Changes proposed in this Pull Request:
- Build a ES package instead of commonjs package.
- Add a top-level `BLUIColors` var to the colors package.

#### To Test:
- Checkout the showcase branch `feature/use-beta-package-colors` run `yarn && yarn start`.
This showcase demo uses a manually published beta package made from this branch.  Demo should work as before & build/serve without a warning sourced from the colors package.

### CODE REVIEW

**Comment by ektasawant** [comment]
Still showing warning on my local.
Screenshot 2022-04-14 at 5 21 35 PM
yarn.lock contains double color packages. I will try with yarn cache clean.
Screenshot 2022-04-14 at 5 26 16 PM

**Comment by emclaug2** [comment]
That warning is from the @brightlayer-ui/ng-progress-icons package & not @brightlayer-ui/colors; there used to be 2 separate warnings.

**Comment by ektasawant** [comment]
> That warning is from the @brightlayer-ui/ng-progress-icons package & not @brightlayer-ui/colors; there used to be 2 separate warnings.

Thanks for clarification. Changes are working fine .

**Review by ektasawant — APPROVED** [review]

**Review by jeffvg — APPROVED** [review]
looks good, no warning for colors

**Pull request merged**
